language: php

notifications:
  email:
    on_success: never

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly
    - script: vendor/bin/phpcs

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - composer self-update

install:
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then composer require "phpunit/phpunit:5.7"; fi

before_script:
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - find src tests \( -name '*.php' \) -exec php -l {} \;
  - vendor/bin/phpunit
  - if [[ $TRAVIS_PHP_VERSION == "7.3" ]]; then vendor/bin/phpcs; fi
